
package mini_progect.mini;
import com.mycompany.tp6_part2.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amine
 */
public class Main_Home extends javax.swing.JFrame {

    /**
     * Creates new form mini_j_frame
     */
    public static Institution Esi = null;
    public static ArrayList<TP_Salle> salles = new ArrayList<> ();
    int Current_Salle_TP_Index;
    
    
    public static void Institustion_init() {
        String logo = "https://www.esi-sba.dz/fr/wp-content/uploads/2020/10/Logo-Complet-ESI-SBA-200mm-x-200mm_couleur-500x500.png";
        // create the Esi-sba institution
        Institution Esi = new Institution(0, "High School", "8 Mai 1945-Sidi-bel-abbes", "+21348749452 ", logo);
        // create new department called second cycle
        Departement second_cycle = new Departement(0, "second cycle", "code", "Amrane abdelkader", "contact_sc@esi-sba.dz");
        
        Departement preparatory_class = new Departement(1, "preparatory class", "code", "Aced", "contact_pre@esi-sba.dz");
        Departement departements[] = {preparatory_class, second_cycle};
        // add the second cycle department to Esi institution

        // creation of one service the teaching service
        Service TeachingServise = new Service_Teaching("2023", "200", "01/09/2023", "01/06/2024");
        // creation of one block that will holds the salles or even Amphis
        Block block_A1 = new Block("A1", "left", "white");
        // creation of one amphi called AmphiA
        Amphitheater AmphiA = new Amphitheater(0, "Amphi D", 100.0, 1000, true);
        
        
        second_cycle.setBlocks(block_A1);
        Esi.setDepartement(departements);

        Main_Home.Esi = Esi;
   
    
    }
    
    public static void Tp_salles_init() {
        TP_Salle Salle_TP = new TP_Salle("20 Tables", 0, "Salle TP 01", 20.0, 20, true);
        // creating of set of computers and one datashow
        Materials PC1 = new PC(01, "AC255-GGH-20", "03-01-2022", "i7", "16G");
        Materials PC2 = new PC(02, "AC2F5-ALH-15", "03-01-2022", "i5", "32G");
        Materials PC3 = new PC(03, "ACHK5-HGH-19", "03-01-2022", "i3", "4G");
        Materials PC4 = new PC(04, "DFRTG-DGE-17", "03-01-2022",  "i9", "16G");
        Materials datashow = new DataShow(01,"1122352512", "03-01-2022" , "Epson");
        Materials printer = new Printer(01, "1122352512", "03-01-2022", "Epson", 2);
        // add the matiriels to our Tp salle
        Salle_TP.add_material_to_TPSalle(PC1);
        Salle_TP.add_material_to_TPSalle(PC2);
        Salle_TP.add_material_to_TPSalle(PC3);
        Salle_TP.add_material_to_TPSalle(PC4);
        Salle_TP.add_material_to_TPSalle(datashow);
        Salle_TP.add_material_to_TPSalle(printer);
        salles.add(Salle_TP);
        
    }
    
    public static void load_Departements() {
        for (int i = 0; i < Esi.dpt_list.size(); i++) {
              DepartementComboBox.addItem(Esi.dpt_list.get(i).DepartmentName);
        }
    }
    
    public static void load_Salles() {

        DefaultListModel MyLstModel = new DefaultListModel();
        for (TP_Salle salle : salles) {
            MyLstModel.addElement(salle.building_name);
        }        
        TP_Salles_Jlist.setModel(MyLstModel);
    }
    
    public static void print_salle_materials(ArrayList<Materials> tp_materials) {
        DefaultTableModel model = (DefaultTableModel) Material_Table_Affiche.getModel();

        if (tp_materials.isEmpty()) {
            model.setRowCount(0);
        } else {

            model.setRowCount(tp_materials.size());
            for (Materials tp_material : tp_materials) {
                model.removeRow(0);
                Object[] rowData = {tp_material.regestration_number, tp_material.date_installation, "", tp_material.type};
                model.addRow(rowData);
               
                
                tp_material.print_material_infos(tp_material);
            }
        }
    }
    
    
    public Main_Home() {        
        initComponents(); // Auto generate by NetBeans IDE
        this.setLocationRelativeTo(null); // to show the frame on the middle of the screen
        Institustion_init(); // To initialize a hard-coded institution and department
        load_Departements(); // To display the departement names  
        Tp_salles_init(); // To initialize a dummy Tp salle 01 with its materials
        load_Salles(); // To Display the existing (dummy salles) to their JList
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepartementComboBox = new javax.swing.JComboBox<>();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TP_Salles_Jlist = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Material_Table_Affiche = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Dep_name_label = new javax.swing.JLabel();
        Dep_code_label = new javax.swing.JLabel();
        Dep_head_label = new javax.swing.JLabel();
        Dep_email_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Dep_services_label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DepartementComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select departement" }));
        DepartementComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartementComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TP_Salles_Jlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TP_Salles_Jlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TP_Salles_JlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TP_Salles_Jlist);

        jButton1.setText("+Create TP room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-Delete TP room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Material_Table_Affiche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Regestration Number", "Installation date", "Name/cpu/ram", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Material_Table_Affiche);

        jLabel1.setText("All Materials");

        jButton3.setText("Add new material");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete selected material");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Dep_name_label.setForeground(new java.awt.Color(255, 255, 255));
        Dep_name_label.setText("Name: ");

        Dep_code_label.setForeground(new java.awt.Color(255, 255, 255));
        Dep_code_label.setText("Code: ");

        Dep_head_label.setForeground(new java.awt.Color(255, 255, 255));
        Dep_head_label.setText("Head of deartement: ");

        Dep_email_label.setForeground(new java.awt.Color(255, 255, 255));
        Dep_email_label.setText("Email address: ");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Departement information");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("name");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("code");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Head of departement");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email address");

        Dep_services_label.setForeground(new java.awt.Color(255, 255, 255));
        Dep_services_label.setText("Number of services: ");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Number of services");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dep_email_label)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dep_head_label)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dep_code_label)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dep_name_label)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dep_services_label)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dep_name_label)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dep_code_label)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dep_head_label)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dep_email_label)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dep_services_label)
                    .addComponent(jLabel12))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(DepartementComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(534, 534, 534))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(737, 737, 737))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DepartementComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedTp_salle = -1;
        selectedTp_salle = TP_Salles_Jlist.getSelectedIndex();
        this.Current_Salle_TP_Index = selectedTp_salle;
        
        if (selectedTp_salle != -1){
            
            //ArrayList<Materials> tp_materials = salles.get(selectedTp_salle).getTp_Materials();
            //print_salle_materials(tp_materials);
            salles.remove(selectedTp_salle);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AddSalleTP().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DepartementComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartementComboBoxActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_DepartementComboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new AddMaterial_tp().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TP_Salles_JlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TP_Salles_JlistMouseClicked
        // TODO add your handling code here:
        int selectedTp_salle = -1;
        selectedTp_salle = TP_Salles_Jlist.getSelectedIndex();
        this.Current_Salle_TP_Index = selectedTp_salle;
        
        if (selectedTp_salle != -1){
            
            ArrayList<Materials> tp_materials = salles.get(selectedTp_salle).getTp_Materials();
            print_salle_materials(tp_materials);
        }
        
    }//GEN-LAST:event_TP_Salles_JlistMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Home().setVisible(true);
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dep_code_label;
    private javax.swing.JLabel Dep_email_label;
    private javax.swing.JLabel Dep_head_label;
    private javax.swing.JLabel Dep_name_label;
    private javax.swing.JLabel Dep_services_label;
    private static javax.swing.JComboBox<String> DepartementComboBox;
    public static javax.swing.JTable Material_Table_Affiche;
    private static javax.swing.JList<String> TP_Salles_Jlist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
